version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: antigcast_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  antigcast_bot:
    build: .
    container_name: antigcast_bot
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - BOT_TOKEN_UTAMA=your_bot_utama_token_here
    depends_on:
      - mongo

volumes:
  mongo_data:
